"""
GUI Styling
"""

# Theme colors
PRIMARY_COLOR = "#2E86AB"
SECONDARY_COLOR = "#A23B72"
SUCCESS_COLOR = "#06A77D"
ERROR_COLOR = "#C73E1D"
BACKGROUND_COLOR = "#F1F1F1"

# Fonts
FONT_FAMILY = "Segoe UI"
FONT_SIZE_LARGE = 14
FONT_SIZE_NORMAL = 12
FONT_SIZE_SMALL = 10
